{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <form action="{:request()->url()}" class="layui-form" method="post">
            <div class="layui-form-item">
                <label class="layui-form-label">商户号</label>
                 <div class="layui-form-mid layui-word-aux text-primary">{$data['shopid']}</div>
            </div>
			<div class="layui-form-item">
                <label class="layui-form-label">实名认证</label>
                 <div class="layui-form-mid layui-word-aux text-primary">{$data['user']}</div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">提现账户</label>
               <div class="layui-form-mid layui-word-aux text-primary">{$data['bankname']}---{$data['accounts']}</div>
            </div>
			<div class="layui-form-item">
                <label class="layui-form-label">实际金额</label>
               <div class="layui-form-mid layui-word-aux text-danger">{$data['money']}-{$data['price']}={$data['money']-$data['price']}</div>
            </div>
			<div class="layui-form-item">
				<label class="layui-form-label">失败原因</label>
				<div class="layui-input-inline" style="width:300px">
					<textarea name="content" placeholder="请输入内容" rows="3" class="layui-textarea">{$data['content']|default=""}</textarea>
				</div>
				<div class="layui-input-inline layui-input-company"></div>
			</div>
			
            <div class="layui-form-item">
                <div class="layui-input-block">
				<input type="hidden" name="type" value="fail">
                <button class="layui-btn ajax-action" href="{:url('/Cash/edit',['type'=>'shou','id'=>$data.id])}">手动打款</button>
				<button class="layui-btn layui-btn-warm" lay-filter="i" lay-submit="">审核失败</button>
				<button class="layui-btn layui-btn-danger ajax-action" href="{:url('/Cash/edit',['type'=>'auto','id'=>$data.id])}">自动打款</button>
                </div>
            </div>
        </form>
    </div>
</div>
{/block}
