<?php
namespace app\common\controller;

use think\facade\View;
use think\facade\Request;
use think\facade\Config as Con;
use app\common\model\Article;
use app\common\model\CardModel;
use app\common\model\CardList;
use app\common\model\Sysconfig;
use app\common\model\User;


class UserBase extends Base
{
    protected $noLogin = []; // 不用权限认证和登录的方法
    protected $noAuth = []; // 不用权限认证要登录的方法
    public $real=[];
	public $config=[];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        !$this->checkLogin() && $this->redirect(url('home/Login/login'));
        $res=Sysconfig::select()->toArray();
		$list=[];
		foreach($res as $k=>$v){
			$list[$v['name']]=$v['value'];
		}
		$this->config=$list;
		$wx = Con::load('setting/weixin','weixin');
		$wxapp = Con::load('setting/wxapp','wxapp');
		$aly = Con::load('setting/aly','aly');
		$this->real=$aly;
		$news=Article::where(['status'=>1,'is_top'=>1])->select();
		$cardModel=CardModel::with('comments')->order("sort_order desc,id desc")->select()->toArray();
		foreach($cardModel as $k=>$v){
			if($v['istype']==1){
				$cardModel[$k]['comments']=CardList::where(['is_hot'=>1])->select()->toArray();
			}
		}
		$shiming=0;
		if($id=is_user_login()){
			$this->user=User::with('userReal')->where(['id'=>$id,'token'=>session("user_auth.token"),'status'=>1])->whereTime('timeout','>',time())->find();
			if(!$this->user){
				//session('user_auth', null);
                //session('user_auth_sign', null);
			}
			if(empty($this->user['userReal']['retype']) && isset($this->real['iska']) && $this->real['iska']==1)$shiming=1;
		}
		$isqq=con::load('setting/qq','qq');
		View::assign('isapi',isset($aly['isapi'])?$aly['isapi']:'');
		View::assign('isqq',$isqq['qqlogin']);
		View::assign('shi',$shiming);
		View::assign("contr",Request::controller());
        View::assign("action",Request::action());
		View::assign("C",array_merge($list,$wxapp));
		View::assign("wx",$wx);
		View::assign("thisli",$news);
		View::assign("user",$this->user);
		View::assign("cardModel",$cardModel);
    }

    // 检查登录
    public function checkLogin()
    {
        if (!is_user_login() &&
            !in_array($this->request->action(), $this->noLogin)) {
            return false;
        }
        return true;
    }
}
