{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <form action="{:request()->url()}" class="layui-form" method="post">
            <div class="layui-form-item">
                <label class="layui-form-label">验证码</label>
                <div class="layui-input-inline">
                    <input type="text" name="code" value="" autocomplete="off" placeholder="" lay-verify="required" class="layui-input">
                </div>
            </div>
			<div class="layui-form-item">
			<label class="layui-form-label">选择验证方式</label>
                <div class="layui-input-inline" style="width: 400px;">
                            <input type="checkbox" name="type" lay-skin="switch" lay-filter="switchTest" lay-text="手机验证|邮箱验证" >
                 </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
				   <a href="{:url('/Security/sendmsg',['type'=>'email'])}" class="layui-btn layui-btn-danger  ajax-action" >获取验证码</a>
                    <button class="layui-btn" lay-filter="*" lay-submit="">提交</button>
                </div>
            </div>
        </form>
    </div>
</div>
{/block}
	{block name="js"}
	<script>
    layui.use(['form', 'layedit', 'laydate'], function(){
		  var form = layui.form
		  ,layer = layui.layer;
		  var photo="{:url('/Security/sendmsg',['type'=>'mobile'])}",email="{:url('/Security/sendmsg',['type'=>'email'])}";
	 form.on('switch(switchTest)', function(data){
		 if(!this.checked){
			 $(".ajax-action").attr("href",email);
			 layer.tips('当前选择验证方式为邮箱验证', data.othis);
		 }else{
			 $(".ajax-action").attr("href",photo);
			 layer.tips('当前选择验证方式为手机验证', data.othis)
		 }
		});
	})
	</script>
	{/block}
