<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>点卡综合后台管理</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <link rel="stylesheet" href="/static/simple/hqui/libs/layui/css/layui.css"/>
    <link rel="stylesheet" href="/static/simple/hqui/module/admin.css?v=316"/>
  <link rel="stylesheet" href="/static/simple/css/fonts.css">
  <link rel="stylesheet" href="/static/simple/css/base.css">
  {block name="css"}{/block}
</head>
<body>
{block name="body"}{/block}
<script type="text/javascript" src="/static/simple/hqui/libs/layui/layui.all.js"></script>
<script type="text/javascript" src="/static/simple/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/simple/js/layui.base.js"></script>
<script type="text/javascript" src="/static/simple/hqui/js/common.js?v=316"></script>
{block name="js"}{/block}
</body>
</html>