<!DOCTYPE html>
<html>
<head>
<title>登陆-后台管理系统</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/simple/hqui/libs/layui/css/layui.css">
<link href="/static/simple/admin/login/css/style.css" rel='stylesheet' type='text/css' />
</head>
<body>
<div class="main">
    <div class="login">
        <h1>易收卡后台管理系统</h1>
        <div class="inset">
            <!--start-main-->
            <form class="layui-form" id="loginForm" action="{:url('/login/index')}" method="post">
                <div>
                    <h2>账户登录</h2>
                    <span><label>用户名</label></span>
                    <span><input type="text" name="username" id="username" lay-verify="required" autocomplete="off" class="layui-input"></span>
                 </div>
                 <div>
                    <span><label>密码</label></span>
                    <span><input type="password" name="password" id="password" lay-verify="required" autocomplete="off" class="layui-input"></span>
                 </div>
				 {switch name="safe.isyan"}
					 {case value="1"}
						 <div>
							<span><label>手机验证码</label></span>
							<span><input type="text" style="width: 50%;float: left;" name="code" id="code" lay-verify="required" autocomplete="off" class="layui-input">
							<button  class="layui-btn layui-btn-danger" id="getcode" style="margin-top: 3px;margin-left: 8px;" type="button">获取验证码</button>
								</span>
						 </div>
						 <input type="hidden" name="type" value="mobile">
				    {/case}
					{case value="2"}
						 <div>
							<span><label>邮箱验证码</label></span>
							<span><input type="text" style="width: 50%;float: left;" name="code" id="code" lay-verify="required" autocomplete="off" class="layui-input">
							<button  class="layui-btn layui-btn-danger" id="getcode" style="margin-top: 3px;margin-left: 8px;" type="button" >获取验证码</button>
								</span>
						 </div>
						 <input type="hidden" name="type" value="email">
				    {/case}
					{/switch}
                <div style="clear:both">
                    <span><input type="checkbox" name="remember_user" id="remember_user" checked title="记住密码"  lay-skin="primary"></span>
                </div>
                <div class="sign">
				    {:token_field()}
                    <button class="layui-btn layui-btn-fluid" lay-submit lay-filter="login">登录</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="copy-right">
    <p>&copy; 2016-2020 <a href="http://www.aixiaoka.net/">易收卡</a> All Rights Reserved</p>

</div>

<script src="/static/simple/user/login/js/jquery.js"></script>
<script src="/static/simple/js/jquery.cookie.js"></script>
<script src="/static/simple/user/login/js/agree.js"></script>
<script src="/static/simple/hqui/libs/layui/layui.js"></script>
<script>
    layui.use(['layer', 'form', 'jquery'], function(){
        var layer = layui.layer,
            form  = layui.form,
            $     = layui.jquery;
            
        form.on('submit(login)', function(data) {
            var index = layer.msg('登录中，请稍候', {
                icon: 16,
                time: false,
                shade: 0.3
            });
            if ($("#remember_user").prop("checked") == true) {
                    var user_name = $("#username").val();
                    var user_password = $("#password").val();
                    $.cookie("remember_user", "true", {
                            expires: 7
                    }); // 存储一个带7天期限的 cookie
                    $.cookie("user_name", user_name, {
                            expires: 7
                    }); // 存储一个带7天期限的 cookie
                    $.cookie("user_password", user_password, {
                            expires: 7
                    }); // 存储一个带7天期限的 cookie
            } else {
                    $.cookie("remember_user", "false", {
                            expires: -1
                    }); // 删除 cookie
                    $.cookie("user_name", '', {
                            expires: -1
                    });
                    $.cookie("user_password", '', {
                            expires: -1
                    });
            }
            $.ajax({
                url: data.form.action,
                type: data.form.method,
                dataType: 'json',
                data: $(data.form).serialize(),
                success: function(result) {
                    if (result.code === 1) {
                        location.href = result.url;
                    } else {
                        $("input[name=__token__]").val(result.token);
                        layer.close(index);
                        layer.msg(result.msg);
                    }
                },
                error: function (xhr, state, errorThrown) {
                    layer.close(index);
                    layer.msg(state + '：' + errorThrown);
                }
            });
            
            return false;
        });
        //
        
    });
  
</script>
<script>
    $(function() {
	if ($.cookie("remember_user")) {
		$("#remember_user").prop("checked", true);
		$("#username").val($.cookie("user_name"));
		$("#password").val($.cookie("user_password"));
                // 输入框内容变化按钮颜色发生变化
                $(".form-data input").siblings("label").hide();
                $(".log-btn").removeClass("off")
	}
});

$("#getcode").click(function(){
	var user=$("#username").val(),pass=$("#password").val(),type=$("input[name=type]").val(),token=$("input[name=__token__]").val();
	if(user=="" || user==null){
		layer.msg("请填写账号");
		return;
	}
	if(pass=="" || pass==null){
		layer.msg("请填写密码");
		return;
	}
	var index = layer.msg('正在发送，请稍候', {
                icon: 16,
                time: false,
                shade: 0.3
            });
	$.post("{:url('/login/sendmsg')}",{username:user,password:pass,type:type,__token__:token},function(e){
		layer.close(index);
		layer.msg(e.msg);
		$("input[name=__token__]").val(e.token);
	})
})
</script>
</body>
</html>