{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <table id="tableList" lay-filter="tableList"></table>
    <!-- 表格操作列 -->
    <script type="text/html" id="tableTBTrack">
        <a href="{:url('/Admin/delopinion')}?id={{d.id}}" class="layui-btn layui-btn-danger layui-btn-sm ajax-delete">删除</a>
    </script>
    <!-- 权限列 -->
    <script type="text/html" id="status">
        <input type="checkbox" name="status" lay-skin="switch" lay-filter="*" lay-text="已读|未读" data-url="{:url('/Admin/editopinion')}?id={{d.id}}" {{d.status==1?'checked':''}}>
    </script>
	<script type="text/html" id="shopid">
     {{#  if(d.shopid > 0){ }}
		 {{d.shopid}}
	   {{#  } else { }}
	   游客
	   {{# }}}
	   </script>
</div>
{/block}

{block name="js"}
<script>
    layui.use(['layer', 'form', 'table', 'util', 'dropdown'], function () {
        var $ = layui.jquery;
        var layer = layui.layer;
        var form = layui.form;
        var table = layui.table;
        var util = layui.util;
        var admin = layui.admin;
        var dropdown = layui.dropdown;

        // 渲染回访表格
        var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/Admin/opinion')}",
            page: true,
            cellMinWidth: 100,
            limit:'15',
            limits:['15','30','50','100','200','500'],
            size:'lg',even:true,
            cols: [[
                {type:'numbers',title:'#'},
                {field: 'type', align: 'left', sort: true, title: '卡类'},
				{templet:'#shopid', align: 'left', sort: true, title: '用户'},
                {field: 'title', align: 'left', sort: true, title: '标题'},
                {field: 'content', align: 'center', sort: true, title: '内容'},
                {field: 'contact', align: 'center', sort: true, title: '联系方式'},
                {field: 'create_time', align: 'center', sort: true, title: '创建时间'},
                {align: 'center', sort: true, title: '状态',templet:'#status',width:100},
                {align: 'center', toolbar: '#tableTBTrack', title: '操作', minWidth: 190}
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.total, //解析数据长度
                  "data": res.data.data //解析数据列表
                };
            }
        });

    });

</script>
{/block}