{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <form action="{:request()->url()}" class="layui-form" method="post">
            <div class="layui-form-item">
                <label class="layui-form-label">银行名称</label>
                <div class="layui-input-block">
                    <input type="text" name="bankName" value="{$data.bankName|default=''}" autocomplete="off" placeholder="请输入银行名称" lay-verify="required" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">银行代码</label>
                <div class="layui-input-block">
                    <input type="text" name="abbr" value="{$data.abbr|default=''}" autocomplete="off" lay-verify="required" placeholder="请输入银行代码"  class="layui-input">
                </div>
            </div>
           <div class="layui-form-item">
                <label class="layui-form-label">PC端图标</label>
                <div class="layui-input-block">
                    <div class="layui-upload-list">
                        <img class="layui-upload-img" id="test-upload-normal-img" src="{$data.logo|default=''}" width="80%" height="80">
                    </div>
                    <input type="hidden" name="logo" value="{$data.logo|default=''}" autocomplete="off" placeholder="" class="layui-input">
                    <button type="button" class="layui-btn ajax-avatar"><i class="fa fa-file-image-o"></i> 选择图片</button>
                </div>
            </div>
			 <div class="layui-form-item">
                <label class="layui-form-label">WAP端图标</label>
                <div class="layui-input-block">
                    <div class="layui-upload-list">
                        <img class="layui-upload-img" id="test-upload-normal-img" src="{$data.logo1|default=''}" width="80%" height="80">
                    </div>
                    <input type="hidden" name="logo1" value="{$data.logo1|default=''}" autocomplete="off" placeholder="" class="layui-input">
                    <button type="button" class="layui-btn ajax-avatar"><i class="fa fa-file-image-o"></i> 选择图片</button>
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-filter="i" lay-submit="">保存</button>
                    <button class="layui-btn layui-btn-primary" type="reset">重置</button>
                </div>
            </div>
        </form>
    </div>
</div>
{/block}
