{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-header">
        <div class="layui-btn-group">
            <a href="{:url('/card/add')}" class="layui-btn ajax-iframe" data-width="750px" data-height="500px"><i class="fa fa-plus-circle"></i> 添加分类</a>
        </div>
    </div>
    
    <table id="tableList" lay-filter="tableList"></table>
    <!-- 表格操作列 -->
    <script type="text/html" id="tableTBTrack">
        <a href="{:url('/card/edit')}?id={{d.id}}" class="layui-btn layui-btn-normal ajax-iframe" data-width="750px" data-height="500px">编辑</a>
        <a href="{:url('/card/del')}?id={{d.id}}" class="layui-btn layui-btn-danger ajax-delete">删除</a>
    </script>
     <script type="text/html" id="istype">
                <input type="checkbox" name="istype" lay-skin="switch" lay-filter="*" lay-text="综合|独立" data-url="{:url('/card/edit')}?id={{d.id}}" {{d.istype==1?'checked':''}}>
     </script>
	 <script type="text/html" id="status">
                <input type="checkbox" name="status" lay-skin="switch" lay-filter="*" lay-text="显示|隐藏" data-url="{:url('/card/edit')}?id={{d.id}}" {{d.status==1?'checked':''}}>
     </script>
	<script type="text/html" id="image">
		<img src="{{d.image}}">
	</script>
	<script type="text/html" id="isauto">
          <input type="checkbox" name="istype" lay-skin="switch" lay-filter="*" lay-text="图片|卡密" data-url="{:url('/card/edit')}?id={{d.id}}" {{d.istype==1?'checked':''}}>
            </script>
    <!-- 权限列 -->
    <script type="text/html" id="sort">
        <input type="text" name="sort_order" value="{{d.sort_order}}" autocomplete="off" class="layui-input ajax-update" data-url="{:url('/card/edit')}?id={{d.id}}">
    </script>
	<script type="text/html" id="icon">
        <input type="text" name="icon" value="{{d.icon}}" autocomplete="off" class="layui-input ajax-update" data-url="{:url('/card/edit')}?id={{d.id}}">
    </script>
	<script type="text/html" id="route">
        <input type="text" name="route" value="{{d.route}}" autocomplete="off" class="layui-input ajax-update" data-url="{:url('/card/edit')}?id={{d.id}}">
    </script>
    
    
</div>
{/block}

{block name="js"}
<script>
    layui.use(['layer', 'form', 'table', 'util', 'dropdown'], function () {
        var $ = layui.jquery;
        var layer = layui.layer;
        var form = layui.form;
        var table = layui.table;
        var util = layui.util;
        var admin = layui.admin;
        var dropdown = layui.dropdown;

        // 渲染回访表格
        var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/card/index_json')}",
            page: false,
            cellMinWidth: 100,
            size:'lg',even:true,
            cols: [[
                {type:'numbers',title:'#'},
                {field: 'title',align: 'content', sort: true, title: '分类名称'},
                {templet:'#image', align: 'content', sort: true, title: '图片'},
				{align: 'center', sort: true, title: '大图标',templet:'#icon',width:200},
				{align: 'center', sort: true, title: '小图标',templet:'#route',width:100},
				{align: 'center', sort: true, title: '分类类型',templet:'#istype'},
                {align: 'center', sort: true, title: '是否显示',templet:'#status'},
                {align: 'center', sort: true, title: '排序',templet:'#sort',width:150},
                {align: 'center', toolbar: '#tableTBTrack', title: '操作', minWidth: 200}
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data, //解析数据长度
                  "data": res.data //解析数据列表
                };
            }
        });

    });

</script>
{/block}