{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <form action="{:request()->url()}" class="layui-form" method="post">
            <div class="layui-form-item">
                <label class="layui-form-label">分类名称</label>
                <div class="layui-input-block">
                    <input type="text" name="title" value="{$data.title|default=''}" autocomplete="off" placeholder="请输入分类名称" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">分类图标</label>
                <div class="layui-input-block">
                    <input type="text" name="image" value="{$data.image|default=''}" autocomplete="off" placeholder="请上传分类图标" class="layui-input">
                    <button type="button" class="layui-btn layui-btn-primary layui-btn-position ajax-images"><i class="fa fa-file-image-o"></i> 选择图片</button>
                </div>
            </div>
			<div class="layui-form-item">
					<label class="layui-form-label">综合分类</label>
					<div class="layui-input-block">
						<input type="radio" name="istype" value="0" title="独立" {eq name="$data.istype|default=0" value="0"}checked{/eq}/>
						<input type="radio" name="istype" value="1" title="综合" {eq name="$data.istype|default=0" value="1"}checked{/eq}/>
					</div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">关键字</label>
                <div class="layui-input-block">
                    <input type="text" name="keywords" value="{$data.keywords|default=''}" autocomplete="off" placeholder="请输入关键字" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">描述</label>
                <div class="layui-input-block">
                    <textarea name="description" autocomplete="off" placeholder="请输入描述" class="layui-textarea">{$data.description|default=''}</textarea>
                </div>
            </div>
           
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-filter="i" lay-submit="">保存</button>
                    <button class="layui-btn layui-btn-primary" type="reset">重置</button>
                </div>
            </div>
        </form>
    </div>
</div>
{/block}
{block name="js"}
<script>
    form.on('select(pid)', function(data){
        var that = $(this);
        var cid = data.value;
        $.ajax({ 
            type: 'POST',
            url: "{:url('/category/get_pcategory')}",
            data:{id:cid},
            success:function(ret) {
                console.log(ret.data);
                $('#model').empty();
                $('#model').append("<option value="+ret.data.model+">"+ret.data.name+"</option>");
                form.render('select');
            },
            dataType:'json',
        });
    });
</script>
{/block}

