{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-header">参数配置</div>
    <div class="layui-card-body" pad15>
        <div class="layui-tab">
            <ul class="layui-tab-title">
                <li><a href="{:url('/config/param',['model'=>'qiniu'])}">七牛配置</a></li>
                <li><a href="{:url('/config/param',['model'=>'qq'])}">QQ登陆配置</a></li>
                <li><a href="{:url('/config/param',['model'=>'wxapp'])}">APP配置</a></li>
                <li><a href="{:url('/config/param',['model'=>'wxpay'])}">微信支付</a></li>
				 <li><a href="{:url('/config/param',['model'=>'alipay'])}">支付宝配置</a></li>
                <li><a href="{:url('/config/param',['model'=>'qcloudsms'])}">短信配置</a></li>
                <li ><a href="{:url('/config/param',['model'=>'baiduapp'])}">百度数据</a></li>
				<li class="layui-this"><a href="{:url('/config/param',['model'=>'email'])}">邮件配置</a></li>
				<li><a href="{:url('/config/param',['model'=>'cash'])}">提现配置</a></li>
				<li><a href="{:url('/config/param',['model'=>'aly'])}">认证配置</a></li>
            </ul>
            <div class="layui-tab-content">
                <div class="layui-tab-item layui-show">
                    <form action="{:url('/config/param',['model'=>'email'])}" class="layui-form" method="post">
						<div class="layui-form-item">
							<label class="layui-form-label">邮箱服务器</label>
							<div class="layui-input-inline" style="width: 400px;">
								<input type="text" name="stmp" value="{$list.stmp|default=""}" class="layui-input">
							</div>
							<div class="layui-input-inline layui-input-company"></div>
						</div>
						<div class="layui-form-item">
							<label class="layui-form-label">发送端口</label>
							<div class="layui-input-inline" style="width: 400px;">
								<input type="text" name="duankou" value="{$list.duankou|default=""}" class="layui-input">
							</div>
							<div class="layui-input-inline layui-input-company"></div>
						</div>
						<div class="layui-form-item">
							<label class="layui-form-label">是否启用SSL</label>
							<div class="layui-input-inline" style="width: 400px;">
								<input type="checkbox" name="type" lay-skin="switch" lay-text="开启|关闭" {if $list.type=='1'} checked{/if}>
							</div>
							<div class="layui-input-inline layui-input-company"></div>
                        </div>
						<div class="layui-form-item">
							<label class="layui-form-label">邮箱账户</label>
							<div class="layui-input-inline" style="width: 400px;">
								<input type="text" name="user" value="{$list.user|default=""}" class="layui-input">
							</div>
							<div class="layui-input-inline layui-input-company"></div>
						</div>
						<div class="layui-form-item">
							<label class="layui-form-label">发送密钥</label>
							<div class="layui-input-inline" style="width: 400px;">
								<input type="password" name="pass" value="{$list.pass|default=""}" class="layui-input">
							</div>
							<div class="layui-input-inline layui-input-company"></div>
						</div>
						<div class="layui-form-item">
							<label class="layui-form-label">发送模板</label>
							<div class="layui-input-inline" style="width: 800px;">
							    <textarea name="smgtpl" placeholder="请输入内容" rows="28" class="layui-textarea">{$list.smgtpl|default=""}</textarea>
							</div>
							<div class="layui-form-mid layui-word-aux">{$list.smgtpl|raw|default=""}</div>
						</div>
						<div class="layui-form-item">
							<label class="layui-form-label">登陆模板</label>
							<div class="layui-input-inline" style="width: 800px;">
							    <textarea name="login" placeholder="请输入内容" rows="20" class="layui-textarea">{$list.login|default=""}</textarea>
							</div>
							<div class="layui-form-mid layui-word-aux">{$list.login|raw|default=""}</div>
						</div>
						<div class="layui-form-item">
							<div class="layui-input-block">
								<button class="layui-btn" lay-submit  lay-filter="*">确认保存</button>
							</div>
						</div>
                    </form>
                </div>
                
            </div>
            
        </div>
        <div class="layui-form" wid100 lay-filter="">
        
            
            
            
            
        
        </div>
    </div>
</div>
{/block}
{block name="js"}
<script src="https://cdn.bootcss.com/jquery/2.2.3/jquery.min.js"></script>
<script>
    element.on('tab(demo)', function(data){
            var that = $(this);
            var model = data.value;
            console.log(data);
            $.ajax({ 
                type: 'POST',
                url: "/user/charge/get_course_data/",
                data:{course_id:course_id},
                success:function(ret) {    
                    //console.log(ret);
                    that.closest("tr").find("select[name='course_data_id[]']").empty();
                    that.closest("tr").find("select[name='course_data_id[]']").append("<option value=''>请选择专业</option>");
                    $.each(ret, function(i,item){
                        //console.log(item.level);
                        that.closest("tr").find("select[name='course_data_id[]']").append("<option value="+item.id+">"+item.level+"</option>");
                    });
                    form.render('select');
                },
                dataType:'json',
            });
        });
</script>
{/block}
