{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-header">参数配置</div>
    <div class="layui-card-body" pad15>
        <div class="layui-tab">
            <ul class="layui-tab-title">
                <li><a href="{:url('/config/param',['model'=>'qiniu'])}">七牛配置</a></li>
                <li class="layui-this"><a href="{:url('/config/param',['model'=>'qq'])}">QQ登陆配置</a></li>
                <li><a href="{:url('/config/param',['model'=>'wxapp'])}">APP配置</a></li>
                <li><a href="{:url('/config/param',['model'=>'wxpay'])}">微信支付</a></li>
				 <li><a href="{:url('/config/param',['model'=>'alipay'])}">支付宝配置</a></li>
                <li><a href="{:url('/config/param',['model'=>'qcloudsms'])}">短信配置</a></li>
                <li><a href="{:url('/config/param',['model'=>'baiduapp'])}">百度数据</a></li>
				<li><a href="{:url('/config/param',['model'=>'email'])}">邮件配置</a></li>
				<li><a href="{:url('/config/param',['model'=>'cash'])}">提现配置</a></li>
				<li><a href="{:url('/config/param',['model'=>'aly'])}">认证配置</a></li>
            </ul>
            <div class="layui-tab-content">
                <div class="layui-tab-item layui-show">
                    <form action="{:url('/config/param',['model'=>'qq'])}" class="layui-form" method="post">
                 <div class="layui-form-item">
                        <label class="layui-form-label">Appid</label>
                        <div class="layui-input-inline" style="width: 400px;">
                            <input type="text" name="appid" value="{$list.appid|default=''}" class="layui-input">
                        </div>
                        <div class="layui-input-inline layui-input-company"></div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">AppKey</label>
                        <div class="layui-input-inline" style="width: 400px;">
                            <input type="text" name="appkey" value="{$list.appkey|default=''}" class="layui-input">
                        </div>
                        <div class="layui-input-inline layui-input-company"></div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">审核模式</label>
                        <div class="layui-input-inline" style="width: 400px;">
                            <input type="checkbox" name="type" lay-skin="switch" lay-text="开启|关闭" {if $list.type=='1'} checked{/if}>
                        </div>
                        <div class="layui-input-inline layui-input-company"></div>
                    </div>
				<div class="layui-form-item">
                        <label class="layui-form-label">QQ登陆</label>
                        <div class="layui-input-inline" style="width: 400px;">
                            <input type="checkbox" name="qqlogin" lay-skin="switch" lay-text="开启|关闭" {if isset($list.qqlogin) && $list.qqlogin=='1'} checked{/if}>
                        </div>
                        <div class="layui-input-inline layui-input-company"></div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">回掉地址</label>
                        
                        <div class="layui-form-mid layui-word-aux" style="#f00!important;">{$callback} </div>
                    </div>
                    <div class="layui-form-item">
                        <div class="layui-input-block">
                            <button class="layui-btn" lay-submit  lay-filter="*">确认保存</button>
                        </div>
                    </div>
                    </form>
                </div>
                
            </div>
            
        </div>
        <div class="layui-form" wid100 lay-filter="">
        
            
            
            
            
        
        </div>
    </div>
</div>
{/block}
{block name="js"}
<script src="https://cdn.bootcss.com/jquery/2.2.3/jquery.min.js"></script>
<script>
    element.on('tab(demo)', function(data){
            var that = $(this);
            var model = data.value;
            console.log(data);
            $.ajax({ 
                type: 'POST',
                url: "/user/charge/get_course_data/",
                data:{course_id:course_id},
                success:function(ret) {    
                    //console.log(ret);
                    that.closest("tr").find("select[name='course_data_id[]']").empty();
                    that.closest("tr").find("select[name='course_data_id[]']").append("<option value=''>请选择专业</option>");
                    $.each(ret, function(i,item){
                        //console.log(item.level);
                        that.closest("tr").find("select[name='course_data_id[]']").append("<option value="+item.id+">"+item.level+"</option>");
                    });
                    form.render('select');
                },
                dataType:'json',
            });
        });
</script>
{/block}
