{extend name="base" /}
{block name="body"}
<style>
.layui-body-header.show {
    display: block;
}
.layui-form-switch{
	margin-top:0;
}
.lay-span{
	display: block;
    padding: 5px 5px;
    background: #FF5722;
    text-align: center;
    color: #fff;
    border-radius: 3px;
}
.layui-card .layui-card-body .layui-btn-group{
	margin-bottom:0;
}

</style>
<div class="layui-card">
    <div class="layui-card-body">
		<table id="tableList" lay-filter="tableList"></table>
    </div>
</div>


<script type="text/html" id="status">
     <input type="checkbox" name="status" lay-skin="switch" lay-filter="*" lay-text="正常|禁用" data-url="{:url('/user/edit')}?id={{d.id}}" {{d.status==1?'checked':''}}>
</script>
<script type="text/html" id="tableTBTrack">
   <div class="layui-btn-group">
		<button type="button" class="layui-btn" lay-event="bianji">编辑</button>
		<button type="button" class="layui-btn layui-btn-danger" lay-event="del">删除</button>
		</div>
</script>
{/block}
{block name="js"}
<script>
    layui.use(['layer', 'form', 'table', 'util', 'dropdown'], function () {
        var $ = layui.jquery;
        var layer = layui.layer;
        var form = layui.form;
        var table = layui.table;
        var util = layui.util;
        var admin = layui.admin;
        var dropdown = layui.dropdown;
		var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/weixin/gettpl')}",
            page: true,
            limit:15,
            limits:[15,30,45,60,75,90],
            cellMinWidth: 100,
            cols: [[
                {type:'numbers',title:'#'},
                {field: 'tplid',align: 'content', sort: true, title: '模板ID',width:400},
                {field:"title", align: 'content', title: '模板名称',width:180},
				{field:'content', align: 'content', title: '回复内容',width:400},
				{align: 'center',  title: '状态',templet:'#status'},
				{align: 'center',  title: '添加时间',field:"create_time"},
                {align: 'center', toolbar: '#tableTBTrack', title: '操作'}
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.total, //解析数据长度
                  "data": res.data.data //解析数据列表
                };
            }
        });
		
		 table.on('tool(tableList)', function(obj){ //注：tool 是工具条事件名，test 是 table 原始容器的属性 lay-filter="对应的值"
			var data = obj.data //获得当前行数据
			,layEvent = obj.event; //获得 lay-event 对应的值
			switch(layEvent){
				case "bianji":
				  var one=openUrl("编辑消息模板",'600px','450px',"{:Url('/weixin/edit')}?id="+data.id);
				break;
				case "del":
				  layer.confirm('确定删除？', {
						icon: 3,
						title: '提示'
					}, function (index) {
						var index = layer.msg('删除中，请稍候', {
							icon: 16,
							time: false,
							shade: 0.3
						});
						$.ajax({
							url: "{:Url('/user/del')}?id="+data.id,
							type: 'post',
							dataType: 'json',
							success: function (result) {
								if (result.code === 1) {
									insTb.reload();
								}
								layer.close(index);
								layer.msg(result.msg);
							},
							error: function (xhr, state, errorThrown) {
								layer.close(index);
								layer.msg(state + '：' + errorThrown);
							}
						});
					});
				break;
			}
			function openUrl(title,width,height,url){
				var index = layer.open({
						title: title,
						type: 2,
						shadeClose:true,
						area: [width, height],
						content: url,
					})
				return index;
			}
		  });

    });

</script>
{/block}
