{extend name="iframe" /}
{block name="body"}
        <div class="layui-fluid">
            <div class="layui-row layui-col-space15">
                <div class="layui-col-md12">
				<blockquote class="layui-elem-quote layui-text" style="border-left-color:#f60">
				  插件商店可以下载接口API和一下特殊插件，欢迎下载
				</blockquote>
					<div class="layui-progress layui-progress-big" id="progre" style="display:none" lay-showpercent="true" lay-filter="demo">
					  <div class="layui-progress-bar layui-bg-blue" lay-percent="0%" style="width: %;"><span class="layui-progress-text">10%</span></div>
					</div>
				<table id="tableList" lay-filter="tableList"></table>
                </div>
              </div>
            </div>
 <script type="text/html" id="tableTBTrack">
      {{#  if(d.state ==1){ }}
        <button  class="layui-btn layui-btn-disabled">已安装</button>
      {{#  } else { }}
	     <button lay-event="download" class="layui-btn layui-btn-danger">立即下载插件</button>
	   {{# }}}
</script>
{/block}
	{block name="js"}
	<script>
	layui.use(['layer', 'form', 'table', 'util', 'dropdown','element'], function () {
        var $ = layui.jquery;
        var layer = layui.layer;
        var form = layui.form;
        var table = layui.table;
        var util = layui.util;
        var admin = layui.admin;
        var dropdown = layui.dropdown;
        var element = layui.element;
		var insTb = table.render({
            elem: '#tableList',
            url: "{:url('/Upsystem/plugunit')}",
            page: true,
            limit:30,
            limits:[30,45,60,75,90],
            cellMinWidth: 100,
            cols: [[
                {type:'checkbox',title:'#'},
                {field: 'title',align: 'content', sort: true, title: '名称'},
                {field: 'version', align: 'content', title: '版本'},
				{field: 'name', align: 'content', title: '包名'},
				{field: 'size', align: 'content', title: '大小'},
				{field: 'account', align: 'content', title: '更新说明'},
				{field: 'addtime', align: 'content', title: '发布时间'},
                {align: 'center', toolbar: '#tableTBTrack', title: '操作'}
            ]],
            parseData: function(res){ //res 即为原始返回的数据
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.length, //解析数据长度
                  "data": res.data //解析数据列表
                };
            }
        });
        
        table.on('tool(tableList)', function(obj){ //注：tool 是工具条事件名，test 是 table 原始容器的属性 lay-filter="对应的值"
			var data = obj.data //获得当前行数据
			,layEvent = obj.event; //获得 lay-event 对应的值
			var qn=$(this);
			 qn.removeClass('layui-btn-danger').addClass('layui-btn-disabled').text('正在下载文件....');
    		  $.post("{:url('/Download/download')}",{turl:data.route,name:data.name,mulu:data.catalog,ver:data.version},function(e){
    		      if(e.code!=1){
    		          layer.msg(e.msg);
    		      }
    		  });
		  
    	   var intime=setInterval(function(){
    			  $.post("{:url('/Download/getjson')}",{name:data.name},function(a){
    			      if(a.code== -1){
    			          clearInterval(intime);
    			      }
    				  if(a.rate==100 || a.code!=1){
    					  if(a.rate==100){
    					      clearInterval(intime);
    						  qn.text('正在升级....');
    						  var index=layer.load();
    						   $.post("{:url('/Download/gengxin')}",{name:data.name,title:data.title,mulu:data.catalog,ver:data.version},function(e){
    						       layer.close(index);
    						       if(e.code!=1){
                    			       layer.msg(e.msg);
                    				   qn.text('已安装');
                    			   }else{
                    			     layer.msg(e.msg,function(){
                    					 location.reload();
                    				 });
                    			   }
    						   })
    					  }
    					  
    				  }else{
    					   $("#progre").show();
    					   element.progress('demo', parseInt(a.rate)+'%');
    				  }
    			  });
    		  },400);
    	  })
        })

			</script>
		{/block}