{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <form action="{:request()->url()}" class="layui-form" method="post">
            <div class="layui-form-item">
                <label class="layui-form-label">数据库地址</label>
                <div class="layui-input-block">
                    <input type="text" name="host" value="" autocomplete="off" placeholder="" lay-verify="required" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">端口</label>
                <div class="layui-input-block">
                    <input type="number" name="port" value="3306" autocomplete="off" placeholder="3306"  class="layui-input">
                </div>
            </div>
			<div class="layui-form-item">
                <label class="layui-form-label">数据库名</label>
                <div class="layui-input-block">
                    <input type="text" name="sql" value="" autocomplete="off" lay-verify="required" class="layui-input">
                </div>
				
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">数据库用户名</label>
                <div class="layui-input-block">
                    <input type="text" name="user" value="" autocomplete="off" lay-verify="required" class="layui-input">
                </div>
				
            </div>
			<div class="layui-form-item">
                <label class="layui-form-label">数据库密码</label>
                <div class="layui-input-block">
                    <input type="text" name="pass" value="" autocomplete="off" lay-verify="required" class="layui-input">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-filter="i" lay-submit="">开始导入</button>
                    <button class="layui-btn layui-btn-primary" type="reset">重置</button>
                </div>
            </div>
        </form>
    </div>
</div>
{/block}
