{extend name="base" /}
{block name="body"}
<div class="layui-card">
    <div class="layui-card-body">
        <div class="layui-btn-group">
            <a href="{:url('/user/truncate')}" class="layui-btn layui-btn-danger ajax-delete"><i class="fa fa-trash-o"></i> 一键清空</a>
        </div>
        <table class="layui-table layui-form">
            <thead>
                <tr>
                    <th>商户ID</th>
                    <th>客户端</th>
                    <th>会员账号</th>
                    <th>IP地址</th>
					<th>地区</th>
                    <th>备注</th>
                    <th>操作行为</th>
                    <th>操作时间</th>
                </tr>
            </thead>
            <tbody>
                {foreach name="list" item="v" empty="$empty"}
                <tr>
                    <td>{$v.shopid}</td>
                    <td>{if $v.ism=='0'}PC{elseif($v.ism=='1')}移动端{else}微信{/if}</td>
                    <td>{$v.shop_name}</td>
                    <td>{$v.ip}</td>
					<td>{$v.area}</td>
                    <td>{$v.remark}</td>
                    <td>{$v.type}</td>
                    <td>{$v.create_time}</td>
                </tr>
                {/foreach}
            </tbody>
        </table>
        <div class="page">{$list|raw}</div>
    </div>
</div>
{/block}
