{extend name="base" /}
{block name="css"}
<style>
    #treeTbTree {
        height: 100%;
        overflow: auto;
    }

    @media screen and (max-width: 768px) {
        #treeTbTree {
            height: auto;
        }
    }

    /** dtree选中颜色重写 */
    .dtree-theme-item-this {
        background-color: #eeeeee !important;
    }
</style>
<style>
    .ew-iframe-body {
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        overflow: auto;
    }
</style>
{/block}
{block name="body"}
<!-- 正文开始 -->

<div class="layui-row layui-col-space15">
    <!-- 左树 -->
    <div class="layui-col-sm12 layui-col-md4 layui-col-lg2" style="width:25%">
        <div class="layui-card" >
            <div class="layui-card-body mini-bar" id="treeTbTree" style="height: 610px;overflow: scroll;">
			 <div class="layui-btn-container">
			    {foreach name="list" item="vo" key="k" }
				   <button type="button" class="layui-btn layui-btn-primary" value="{$k}" style="width:100%">{$vo.title}</button> 
				{/foreach}
			  </div>
            </div>
        </div>
    </div>
    <!-- 右表 -->
    <div class="layui-col-sm12 layui-col-md8 layui-col-lg10" style="width:75%">
        <div class="layui-card">
		     <div class="layui-inline layui-show-xs-block">
			 <form class="layui-form">
			    <div class="layui-inline">
					<label class="layui-form-label" id="cardname" style="width:130px;text-align:left"></label>
				</div>
				<div class="layui-inline">
					<label class="layui-form-label" id="daima"></label>
				</div>
				<div class="layui-inline">
					<div class="layui-input-block">
					  <input type="checkbox" checked="" name="open" lay-skin="switch" lay-filter="switchTest" lay-text="开启|禁用">
					  <div class="layui-unselect layui-form-switch layui-form-onswitch" lay-skin="_switch"><em>开启</em><i></i></div>
					</div>
				</div>
				</form>
             </div>
		 </div>
            <table id="tableTbTree" lay-filter="tableTbTree"></table>
        </div>
    </div>
</div>

{/block}
{block name="js"}
<script>
    layui.use(['layer', 'form', 'table', 'util', 'dropdown'], function () {
        var $ = layui.jquery;
        var layer = layui.layer;
        var form = layui.form;
        var table = layui.table;
        var util = layui.util;
        var admin = layui.admin;
        var dropdown = layui.dropdown;
		var insTb = table.render({
            elem: '#tableTbTree',
            url: "{:url('/User/getFeilv')}",
            where:{id:{$uid},cid:$("#treeTbTree button:first").attr('value')},
            page: true,
            limit:10,
            limits:[15,30,45,60,75,90],
            cellMinWidth: 100,
            cols: [[
                {type:'numbers',title:'#'},
                {field: 'mian',align: 'content', sort: true, title: '面值'},
				{field: 'feilv', align: 'content', title: '费率',edit:'text'},
            ]],
            parseData: function(res){ //res 即为原始返回的数据
			     $("#cardname").text(res.title);
				 $("#daima").text(res.daima);
				 if(res.open==3){
					 $("input[name=open]").attr('checked',false);
				     $("input[name=open]").next().removeClass('layui-form-onswitch');
					 $("input[name=open]").next().find('em').text('禁用');
				 }else{
					 $("input[name=open]").attr('checked',true);
					 if(!$("input[name=open]").next().hasClass("layui-form-onswitch"))$("input[name=open]").next().addClass('layui-form-onswitch');
					 $("input[name=open]").next().find('em').text('启用');
				 }
                return {
                  "code": res.code, //解析接口状态
                  "msg": res.msg, //解析提示文本
                  "count": res.data.total, //解析数据长度
                  "data": res.data.data //解析数据列表
                };
            }
        });
		 //监听指定开关
		  form.on('switch(switchTest)', function(data){
			var state=this.checked ? 1 : 0;
			var index = layer.msg('正在修改数据，请稍候', {icon: 16,time: false,shade: 0.3});
			$.post("{:url('/User/feilv',['id'=>$uid])}&cid="+$("#daima").text(),{state:state},function(e){
				layer.close(index);
				layer.msg(e.msg);
			})
			
		  });
		  //监听单元格编辑
		  table.on('edit(tableTbTree)', function(obj){
			var value = obj.value //得到修改后的值
			,data = obj.data //得到所在行所有键值
			,field = obj.field; //得到字段
			var index = layer.msg('正在修改数据，请稍候', {icon: 16,time: false,shade: 0.3});
			$.post("{:url('/User/editfeilv',['id'=>$uid])}&cid="+data.id,{field:data.mian,value:value},function(e){
				 layer.close(index);
				layer.msg(e.msg);
			})
		  });
		 $("#treeTbTree").on("click","button",function(){
		    var e=$(this);
			e.siblings().addClass("layui-btn-primary");
			e.removeClass("layui-btn-primary");
			loading =layer.load(1, {shade: [0.1,'#fff']});
            var name=e.attr('value');
			var index = layer.load(3, {
					  shade: [0.1,'#fff'] //0.1透明度的白色背景
					});
                 insTb.reload({
					page:{curr:1},
                    where:{
						 id:{$uid},
						 cid:name
                     }
                 });
				 layer.close(index);
		});
		$("#treeTbTree button:first").removeClass("layui-btn-primary");
    });
</script>
{/block}